### ISSUE TITLE
LV2 plugins let ardour crash

### ISSUE THREAD

**Issue by lolgab** [onkelDead/tascam.lv2#1]
When I add one of the plugins on a track on Ardour 5.10 it crashes and on the command line I can read this:
`ardour-5.10.0: hcontrol.c:823: snd_hctl_elem_read: asserzione "elem" non riuscita.
Annullato (core dump creato)
`

**Comment by onkelDead** [comment]
Hi,
 I'm currently working on a integration of the driver patch in the mainline kernel.
 Thats why tascam.lv2 and the kernel driver patch on github are out of synch.

I'll update the driver patch to the version just released in linux kernel 4.12 asap.

This will bring these components back to synch and they will work perfectly.

Greets
 onkel

**Comment by onkelDead** [comment]
It got fixed right now.

**Comment by lolgab** [comment]
I tried and it works :) :)
