### ISSUE TITLE
Is DSP inline with audio inputs or only in stereo mixer

### ISSUE THREAD

**Issue by riban-bw** [onkelDead/tascam.lv2#5]
Sorry this is a query rather than an issue but I don't see a discussions area.

Everything I read online, including the official specifications seem to suggest that the DSP only applies the signals that are subsquently mixed to a stereo bus. Is this true or can the DSP be applied to individual inputs before they appear as separate USB audio inputs, e.g. 

Input 1 -> DSP -> DAW track 1
Input 2 -> DSP -> DAW track 2
Input 3 -> DSP -> DAW track 3
...

I would like to use these plugins to modify DSP applied to each input before it hits a separate track of the multitrack recorder in the computer. (I do not yet own a US-16x08 but plan to buy one soon, especially if there is a positive outcome to this query.)

**Comment by onkelDead** [comment]
Hi,
from my experience, the Tascam device will operate as you expect.
Each Input owns a separate channel at DSP (eq/compressor) inside the device and might be separately controlled.
Unfort. the lv2 plugin isn't maintained for some time and I heard about some issues.

Greets
onkel

**Comment by riban-bw** [comment]
Great, thanks. I saw the reference manual shows the DSP inline so am sufficiently confident to order the device.

Don't worry about the LV2 support. If I find any issues I will fork and fix them. I intend to use the US-16x08 with zynthian which could provide my dream device. I will post about my success (or otherwise) in the zynthian forum.

Thanks for your help.
